### ISSUE TITLE
Help me with flutter dap?

### ISSUE THREAD

**Issue by DartMitai** [sidlatau/dotfiles#1]
Hi, I'm a beginner in Neovim and I can't configure debug debug Copied part of your config, but the launch is not successful, can you help me?
https://github.com/MitaiDart/dotfiles/tree/master/nvim/lua
![Снимок экрана от 2022-12-16 21-11-08](https://user-images.githubusercontent.com/104931116/208142430-0bf0b41f-0c8f-4ede-91bc-3b25ca17792a.png)

**Comment by MitaiDart** [comment]
dap-log
[ WARN ] 2022-12-17T00:22:47Z+0500 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:965 ]	"No event handler for "	{
  body = vim.empty_dict(),
  event = "flutter.appStarted",
  seq = 6,
  type = "event"
}
[ WARN ] 2022-12-17T00:22:47Z+0500 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:965 ]	"No event handler for "	{
  body = {
    vmServiceUri = "ws://127.0.0.1:40263/99rXZQJkx7A=/.,/ws"
  },
  event = "dart.debuggerUris",
  seq = 8,
  type = "event"
}
[ WARN ] 2022-12-17T00:22:48Z+0500 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:965 ]	"No event handler for "	{
  body = {
    method = "s0.reloadSources",
    service = "reloadSources"
  },
  event = "dart.serviceRegistered",
  seq = 12,
  type = "event"
}
[ WARN ] 2022-12-17T00:22:48Z+0500 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:965 ]	"No event handler for "	{
  body = {
    method = "s0.hotRestart",
    service = "hotRestart"
  },
  event = "dart.serviceRegistered",
  seq = 13,
  type = "event"
}
[ WARN ] 2022-12-17T00:22:48Z+0500 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:965 ]	"No event handler for "	{
  body = {
    method = "s0.flutterVersion",
    service = "flutterVersion"
  },
  event = "dart.serviceRegistered",
  seq = 14,
  type = "event"
}
[ WARN ] 2022-12-17T00:22:48Z+0500 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:965 ]	"No event handler for "	{
  body = {
    method = "s0.compileExpression",
    service = "compileExpression"
  },
  event = "dart.serviceRegistered",
  seq = 15,
  type = "event"
}
[ WARN ] 2022-12-17T00:22:48Z+0500 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:965 ]	"No event handler for "	{
  body = {
    method = "s0.flutterMemoryInfo",
    service = "flutterMemoryInfo"
  },
  event = "dart.serviceRegistered",
  seq = 16,
  type = "event"
}
[ WARN ] 2022-12-17T00:22:48Z+0500 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:965 ]	"No event handler for "	{
  body = {
    method = "s0.flutterGetSkSL",
    service = "flutterGetSkSL"
  },
  event = "dart.serviceRegistered",
  seq = 17,
  type = "event"
}
[ WARN ] 2022-12-17T00:22:48Z+0500 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:965 ]	"No event handler for "	{
  body = {
    method = "s2.reloadSources",
    service = "reloadSources"
  },
  event = "dart.serviceRegistered",
  seq = 18,
  type = "event"
}
[ WARN ] 2022-12-17T00:22:48Z+0500 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:965 ]	"No event handler for "	{
  body = {
    method = "s2.hotRestart",
    service = "hotRestart"
  },
  event = "dart.serviceRegistered",
  seq = 19,
  type = "event"
}
[ WARN ] 2022-12-17T00:22:48Z+0500 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:965 ]	"No event handler for "	{
  body = {
    method = "s2.flutterVersion",
    service = "flutterVersion"
  },
  event = "dart.serviceRegistered",
  seq = 20,
  type = "event"
}
[ WARN ] 2022-12-17T00:22:48Z+0500 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:965 ]	"No event handler for "	{
  body = {
    method = "s2.compileExpression",
    service = "compileExpression"
  },
  event = "dart.serviceRegistered",
  seq = 21,
  type = "event"
}
[ WARN ] 2022-12-17T00:22:48Z+0500 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:965 ]	"No event handler for "	{
  body = {
    method = "s2.flutterMemoryInfo",
    service = "flutterMemoryInfo"
  },
  event = "dart.serviceRegistered",
  seq = 22,
  type = "event"
}
[ WARN ] 2022-12-17T00:22:48Z+0500 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:965 ]	"No event handler for "	{
  body = {
    method = "s2.flutterGetSkSL",
    service = "flutterGetSkSL"
  },
  event = "dart.serviceRegistered",
  seq = 23,
  type = "event"
}
[ WARN ] 2022-12-17T00:22:48Z+0500 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:965 ]	"No event handler for "	{
  body = {
    extension = "ext.flutter.activeDevToolsServerAddress",
    value = "http://127.0.0.1:9102"
  },
  event = "flutter.serviceExtensionStateChanged",
  seq = 24,
  type = "event"
}
[ WARN ] 2022-12-17T00:22:48Z+0500 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:965 ]	"No event handler for "	{
  body = {
    extension = "ext.flutter.connectedVmServiceUri",
    value = "http://127.0.0.1:40263/99rXZQJkx7A=/"
  },
  event = "flutter.serviceExtensionStateChanged",
  seq = 25,
  type = "event"
}
[ WARN ] 2022-12-17T00:22:48Z+0500 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:965 ]	"No event handler for "	{
  body = {
    extension = "ext.flutter.activeDevToolsServerAddress",
    value = "http://127.0.0.1:9104"
  },
  event = "flutter.serviceExtensionStateChanged",
  seq = 26,
  type = "event"
}
[ WARN ] 2022-12-17T00:22:48Z+0500 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:965 ]	"No event handler for "	{
  body = {
    extension = "ext.flutter.connectedVmServiceUri",
    value = "http://127.0.0.1:40263/99rXZQJkx7A=/.,"
  },
  event = "flutter.serviceExtensionStateChanged",
  seq = 27,
  type = "event"
}
